API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/urls.py
from django.urls import path 
from .import views

app_name = 'apis'

urlpatterns = [
path('', views.index, name='index'), 
path('ocr/', views.ocr, name='ocr'), 
path('imageanalysis/', views.imageanalysis, name='imageanalysis'), ]

API/IntegratingMicrosoftComputerVisionAPIwithPython/mscv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apis.urls')),
]

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/models.py
from django.db import models
from django.utils.timezone import now 
from datetime import datetime

# Azure imports
from azure.cognitiveservices.vision.computervision import ComputerVisionClient
from azure.cognitiveservices.vision.computervision.models import VisualFeatureTypes
from azure.cognitiveservices.vision.computervision.models import OperationStatusCodes
from msrest.authentication import CognitiveServicesCredentials
import time

# Create your models here.

class Key_Endpoint(models.Model):
    endpoint = models.URLField(max_length=100,null=True)
    key = models.CharField(max_length=100,null=True)
    def set_endpoint(self, e):
        self.endpoint = e
    def set_key(self, k):
        self.key = k

class OCR(models.Model):
    def set_url(self, url):
        self.image_url = url

    image_url = models.URLField(max_length=500,null=True)

    def ocr(self, k_e = Key_Endpoint):
        computervision_client = ComputerVisionClient(k_e.endpoint,\
                         CognitiveServicesCredentials(k_e.key))
        read_image_url = self.image_url
        try:
            read_response = computervision_client.read(read_image_url,  raw=True)
            read_operation_location = read_response.headers["Operation-Location"]
            operation_id = read_operation_location.split("/")[-1]

            # Call the "GET" API and wait for it to retrieve the results
            while True:
                read_result = computervision_client.get_read_result(operation_id)
                if read_result.status not in ['notStarted', 'running']:
                    break
                time.sleep(1)

            # Print the detected text, line by line
            if read_result.status == OperationStatusCodes.succeeded:
                d = ""
                for text_result in read_result.analyze_result.read_results:
                    for line in text_result.lines:
                        d += line.text + "\n"
                return {"result":"Results","detail":d}
                
            return {"result":"Error","detail":""}
        except:
            return {"result":"Invalid Endpoint or Key.","detail":""}

class ImageAnalysis2(models.Model):
    image_url = models.URLField(max_length=500,null=True)
    process = models.URLField(max_length=100,null=True)

    def set_url(self, url):
        self.image_url = url

    def set_process(self, options):
        print(options, flush=True)
        self.process = options

    def analyse(self, k_e = Key_Endpoint):
        computervision_client = ComputerVisionClient(k_e.endpoint,\
                         CognitiveServicesCredentials(k_e.key))
        read_image_url = self.image_url
        try:
            # GET
            results = []
            # Description
            if  "DESCRIPTION" in self.process:
                description_results = computervision_client.describe_image(read_image_url)
                intro = "Description of the image"
                info = []
                conf = []
                if (len(description_results.captions) == 0):
                    info.append("No description detected.")
                else:
                    for caption in description_results.captions:
                        info.append((caption.text + " \n").capitalize())
                        conf.append(str(int(caption.confidence * 100)) + "%")
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info)   
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})
            
            # Category
            if "CATEGORY" in self.process:
                remote_image_features = ["categories"]
                categorize_results_remote = computervision_client.analyze_image(read_image_url , remote_image_features)

                intro = "Categories from the image"
                info = []
                conf = []
                if (len(categorize_results_remote.categories) == 0):
                    info.append("No categories detected.")
                else:
                    for category in categorize_results_remote.categories:
                        info.append(category.name.capitalize())
                        conf.append(str(int(category.score * 100)) +"%")
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info)   
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})
                

            # Tag
            if "TAG" in self.process:
                tags_result_remote = computervision_client.tag_image(read_image_url)
                intro = "Tags in the image"
                info = []
                conf = []
                if (len(tags_result_remote.tags) == 0):
                    info.append("No tags detected.")
                else:
                    for tag in tags_result_remote.tags:
                        info.append(tag.name.capitalize())
                        conf.append(str(int(tag.confidence * 100)) +"%")
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info)   
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})
            
            # DETECT
            # Object
            if "OBJECT" in self.process:
                detect_objects_results_remote = computervision_client.detect_objects(read_image_url)
                intro = "Detecting objects in the image"
                info = []
                conf = []

                if len(detect_objects_results_remote.objects) == 0:
                    info.append("No objects detected.")
                else:
                    for object in detect_objects_results_remote.objects:
                        print(info,flush=True)
                        info.append(("object at location: "+ str(object.rectangle.x) +", "+ str(object.rectangle.x + object.rectangle.w) +", "+\
                            str(object.rectangle.y) +", and "+ str(object.rectangle.y + object.rectangle.h)).capitalize())
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info)
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})

            # Brands
            if "BRAND" in self.process:
                remote_image_features = ["brands"]
                detect_brands_results_remote = computervision_client.analyze_image(read_image_url, remote_image_features)
                intro = "Detecting brands in the image"
                info = []
                conf = []

                if len(detect_brands_results_remote.brands) == 0:
                    info.append("No brands detected.")
                else:
                    for brand in detect_brands_results_remote.brands:
                        conf.append(str(int(brand.confidence * 100))+"%")

                        info.append((brand.name+ " brand detected at location: "+\
                        str(brand.rectangle.x) + ", " + str(brand.rectangle.x + brand.rectangle.w) +
                        ", "+ str(brand.rectangle.y) +",and "+ str(brand.rectangle.y + brand.rectangle.h)).capitalize())
                        
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info)   
                        
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})

            # Faces
            if "FACES" in self.process:
                remote_image_features = ["faces"]
                detect_faces_results_remote = computervision_client.analyze_image(read_image_url, remote_image_features)
                intro = "Faces in the remote image:  \n"
                info = []
                conf = []
                if (len(detect_faces_results_remote.faces) == 0):
                    info.append("No faces detected.")
                else:
                    for face in detect_faces_results_remote.faces:
                        info.append((str(face.gender) + " of age " + str(face.age) + " at location: "+ str(face.face_rectangle.left) +", "+\
                            str(face.face_rectangle.top) +", "+ str(face.face_rectangle.left + face.face_rectangle.width)+", and "+\
                            str(face.face_rectangle.top + face.face_rectangle.height)).capitalize())
                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info) 
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})

            # Adult
            if "ADULT" in self.process:
                remote_image_features = ["adult"]
                detect_adult_results_remote = computervision_client.analyze_image(read_image_url, remote_image_features)
                intro = "Analyzing remote image for adult or racy content ..."
                info = []
                conf = []
                info.append("Is adult content: "+ str(detect_adult_results_remote.adult.is_adult_content))
                conf.append(str(int(detect_adult_results_remote.adult.adult_score * 100)) + "%")
                info.append("Has racy content: "+ str(detect_adult_results_remote.adult.is_racy_content))
                conf.append(str(int(detect_adult_results_remote.adult.racy_score * 100))  + "%")
                info.append("Has gory content: "+ str(detect_adult_results_remote.adult.is_gory_content))
                conf.append(str(int(detect_adult_results_remote.adult.gore_score * 100))  + "%")

                conf2 = conf
                if len(conf) == 0:
                    conf2 = [""]*len(info) 
                results.append({"intro":intro, "result": zip(info, conf2), "confidence": conf})
            
            # Color scheme in the image
            if "COLOR" in self.process:
                remote_image_features = ["color"]

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/forms.py
from django import forms
from django.forms import widgets 
from .models import Key_Endpoint, OCR, ImageAnalysis2

class OCRForm(forms.ModelForm): 
    class Meta:
        model = OCR
        fields = ['image_url']

class ImageAnalysis2Form(forms.ModelForm): 
    
    ANALYSIS_CHOICES = (
        ("DESCRIPTION", "Description"),
        ("CATEGORY", "Category"),
        ("TAG", "Tag"),
        ("OBJECT", "Detect Object"),
        ("BRAND", "Detect Popular Brand"),
        ("FACES", "Detect Faces"),
        ("ADULT", "Detect Adult, Racy, or Gory Content"),
        ("COLOR","Color Schemes in Images"),
        ("CELEBRITIES","Detect Celebrities"),
        ("LANDMARK","Detect Landmarks"),
        ("TYPE","Detect Image Type")
    )
    select = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                          choices=ANALYSIS_CHOICES)
    class Meta:
        model = ImageAnalysis2
        fields = ['image_url']

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/views.py
from apis.models import Key_Endpoint, OCR, ImageAnalysis2
from .forms import OCRForm, ImageAnalysis2Form
from django.shortcuts import render, redirect
import requests

# Create your views here.

def index(request):
    return render(request, 'apis/index.html')

def ocr(request):
    key_endpoint = Key_Endpoint.objects.all()
    done = "Please enter endpoint and subscription_key"
    data = ""
    img = ""

    if key_endpoint != None:
        key_endpoint = key_endpoint.last()
        done = "You have added the endpoint and subscription_key"

    if request.method != 'POST':
        form = OCRForm()
    else:
        form = OCRForm(request.POST, request.FILES) 
        if form.is_valid():
            form.save()
            obj = OCR()
            img = form.cleaned_data['image_url']
            obj.set_url(img)
            k_e = Key_Endpoint()
            k_e.set_endpoint("{{ENDPOINT}}")
            k_e.set_key("{{SUBSCRIPTION_KEY}}")
            data = obj.ocr(k_e)
    
    context = {"keys_status": done, "form": form, "data": data, "image":img}
    return render(request, 'apis/ocr.html',context)

def imageanalysis(request):
    key_endpoint = Key_Endpoint.objects.all()
    done = "Please enter endpoint and subscription_key"
    data = ""
    img = ""
    if key_endpoint != None:
        key_endpoint = key_endpoint.last()
        done = "You have added the endpoint and subscription_key"

    if request.method != 'POST':
        form = ImageAnalysis2Form()
    else:
        form = ImageAnalysis2Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img = form.cleaned_data['image_url']
            obj = ImageAnalysis2()
            obj.set_url(form.cleaned_data['image_url'])
            obj.set_process(form.cleaned_data['select'])
            k_e = Key_Endpoint()
            k_e.set_endpoint("{{ENDPOINT}}")
            k_e.set_key("{{SUBSCRIPTION_KEY}}")
            data = obj.analyse(k_e)
    
    context = {"keys_status": done,"data": data,"form": form, "image": img}

    return render(request, 'apis/imageanalysis.html', context)

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/templates/apis/imageanalysis.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html style="height: 100%">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% bootstrap_css %} {% bootstrap_javascript jquery='full' %}
    <style>
      #id_image_url {
        display: block;
        width: 70%;
      }
      #id_option {
        display: block;
        height: 30px;
      }
      li {
        list-style-type: none;
      }
      ul {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 5px 7px;
      }
    </style>
  </head>
  <body>
    <div class="bg-dark">
      <h2 style="text-align: center; color: white; margin: 0px">
        Image Analysis App
      </h2>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'apis:ocr' %}">OCR</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'apis:imageanalysis' %}"
              >Analysis</a
            >
          </li>
        </ul>
      </div>
    </nav>
    <div style="margin-left: 20%; margin-top: 5%">
      <h3>Enter details below:</h3>
      <p>{{keys_status}}</p>
      <form method="post" enctype="multipart/form-data">
        <div class="form-group">{% csrf_token %} {{ form.as_p }}</div>
        <button type="submit" class="btn btn-dark">Run</button>
      </form>
      <div style="margin: 5%">
        <div>
          <center>
            <img
              style="max-width: 300px; max-height: 300px"
              src="{{ image }}"
            />
          </center>
        </div>
        <div style="margin-top: 5%; width: 80%">
          {% if data %} {% for result in data %}
          <center><h4>{{result.intro}}</h4></center>
          <div class="table-responsive">
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col" style="width: 5%">#</th>
                  <th scope="col" style="width: 65%">Result</th>
                  <th scope="col">Confidence</th>
                </tr>
              </thead>
              <tbody>
                {% for r,c in result.result %}
                <tr>
                  <th scope="row" style="width: 5%">{{ forloop.counter }}</th>
                  <td style="width: 65%">{{r}}</td>

                  {% if result.confidence %}
                  <td>{{c}}</td>
                  {% else %}
                  <td>---</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endfor %} {% endif %}
          </div>
        </div>
        <div style="padding-bottom: 10%">
          <p>To access the OCR functionality press the button below:</p>
          <br />
          <a class="btn btn-primary" href="{% url 'apis:ocr' %}" role="button"
            >OCR</a
          >
        </div>
      </div>
    </div>
  </body>
</html>

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/templates/apis/index.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html style="height: 100%">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% bootstrap_css %} {% bootstrap_javascript jquery='full' %}
    <style></style>
  </head>
  <body>
    <div class="bg-dark">
      <h2 style="text-align: center; color: white; margin: 0px">
        Image Analysis App
      </h2>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apis:ocr' %}">OCR</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apis:imageanalysis' %}"
              >Analysis</a
            >
          </li>
        </ul>
      </div>
    </nav>

    <div style="margin-left: 20%; margin-top: 5%; margin-right: 20%">
      <h3>About</h3>
      <p>
        This App is a demo for the Microsoft Computer Vision API. <br /><br />
        MS Computer Vision gives access to advanced algorithms for image
        processing and returning information. In this App you can provide a URL
        that is analyzed by the algorithm depending on the inputs and user
        choices.
      </p>
      <h3>Functionalities</h3>
      <p style="padding-bottom: 3%">
        To start you will have to add your subscription_key and endpoint on
        these two by creating a MS Computer Vision resource on Azure.
        <br /><br />
        Following are the functionalities provided in the App: <br />
        <br />
        1. Optical Character Recognition (OCR): <br />
        &emsp; &emsp; &emsp; It includes reading printed and hand-written (only
        English) text from images and PDFs.<br /><br />
        2. Image Analysis: <br />
        &emsp; &emsp; &emsp; - Get Description <br />
        &emsp; &emsp; &emsp; - Get Category <br />
        &emsp; &emsp; &emsp; - Get Tags <br />
        &emsp; &emsp; &emsp; - Get Description <br />
        &emsp; &emsp; &emsp; - Detect Objects <br />
        &emsp; &emsp; &emsp; - Detect Popular Brands <br />
        &emsp; &emsp; &emsp; - Detect Faces <br />
        &emsp; &emsp; &emsp; - Detect Adult, Racy, and Gory Content <br />
        &emsp; &emsp; &emsp; - Get Color Schemes <br />
        &emsp; &emsp; &emsp; - Detect Celebrities <br />
        &emsp; &emsp; &emsp; - Detect Landmarks <br />
        &emsp; &emsp; &emsp; - Detect Image Type <br />
      </p>
      <div style="padding-bottom: 10%;">
        <p> To access these functionalities press the buttons below: </p><br />
        <a 
          class="btn btn-primary" 
          href="{% url 'apis:ocr' %}" 
          role="button"
          >OCR</a>
        <a
          class="btn btn-primary"
          href="{% url 'apis:imageanalysis' %}"
          role="button"
          >Analysis</a>
        </div>
      </div>
  </body>
</html>

API/IntegratingMicrosoftComputerVisionAPIwithPython/apis/templates/apis/ocr.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html style="height: 100%">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% bootstrap_css %} {% bootstrap_javascript jquery='full' %}
    <style>
      #id_image_url{
        display: block;
        width: 70%;
      }
    </style>
  </head>
  <body>
    <div class="bg-dark">
      <h2 style="text-align: center; color: white; margin: 0px">
        Image Analysis App
      </h2>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     
      <div class="navbar" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'apis:ocr' %}">OCR</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apis:imageanalysis' %}"
              >Analysis</a
            >
          </li>
        </ul>
      </div>
    </nav>
    <div style="margin-left: 20%; margin-top: 5%;">
      <h3>Enter details below:</h3>
        <p>{{keys_status}}</p>
        <form method="post" enctype="multipart/form-data">
          <div class="form-group">{% csrf_token %} {{ form.as_p }}</div>
          <button type="submit" class="btn btn-dark">Run</button>
        </form>
        <div style="margin: 5%; display: flex">
          <embed style="max-width: 300px" src="{{ image }}" />
          <div style="margin-left: 5%; margin-right: 5%">
            {% if data %}
              <h3>{{data.result}}</h4>
               <div style="white-space: pre-line;">
              {{data.detail}}
              </div>
            {% endif %}
          </div>
        </div>
        <div style="padding-bottom: 10%;">
          <p> To access the image analysis functionality press the button below: </p><br />
          <a
            class="btn btn-primary"
            href="{% url 'apis:imageanalysis' %}"
            role="button"
            >Analysis</a>
        </div>
      </div>
    </div>
  </body>
</html>