API/ExploringSpacewithNASAapisInPython/demo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('nasapp.urls'))
]

API/ExploringSpacewithNASAapisInPython/nasapp/urls.py
from django.urls import path
from .import views


app_name = 'nasapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('events', views.events, name='events'),
    path('events/<str:id>', views.event, name='event'),
    path('asteroids', views.asteroids, name='asteroids'),
    path('mars', views.mars, name='mars')
]

API/ExploringSpacewithNASAapisInPython/nasapp/views.py
from django.shortcuts import render
from datetime import date
import requests


API_KEY = '{{API_KEY}}'

def index(request):
    url = 'https://api.nasa.gov/planetary/apod'
    headers={
       'api_key': API_KEY
    }
    response = requests.get(url, headers)
    context={
        'picture': response.json()
    }
    return render(request, 'nasapp/index.html', context)

def events(request):
    url = 'https://eonet.gsfc.nasa.gov/api/v3/categories'
    headers={
        'api_key': API_KEY
    }
    response = requests.get(url, headers)
    context={
        'all_categories': response.json()['categories'],
        'selected_categories': ['Sea and Lake Ice', 'Severe Storms', 'Drought', 'Volcanoes', 'Wildfires', 'Earthquakes']
    }
    return render(request, 'nasapp/events.html', context)

def event(request, id):
    url = 'https://eonet.gsfc.nasa.gov/api/v3/events'
    headers={
       'api_key': API_KEY,
       'category': id
    }
    response = requests.get(url, headers)
    context={
        'events': response.json()['events']
    }
    return render(request, 'nasapp/event.html', context)

def asteroids(request):
    start_date = date.today().strftime("%Y-%m-%d")
    url = 'https://api.nasa.gov/neo/rest/v1/feed'
    headers={
        'api_key': API_KEY,
        'start_date': start_date,
        'end_date': start_date
    }
    response = requests.get(url, headers)
    context={
        'asteroids': response.json()['near_earth_objects'][start_date]
    }
    return render(request, 'nasapp/asteroids.html', context)

def mars(request):
    rover = 'Spirit'
    camera = 'navcam'

    if request.method == 'POST':
        rover = request.POST.get('rover')
        camera = request.POST.get('camera')

    url = 'https://api.nasa.gov/mars-photos/api/v1/rovers/'+rover+'/photos?'
    headers={
        'api_key': API_KEY,
        'sol': 45,
        'camera': camera
    }
    response = requests.get(url, headers)
    context={
        'photos': response.json()['photos'],
        'selected_rover': rover,
        'selected_camera': camera
    }
    return render(request, 'nasapp/mars.html', context)

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/asteroids.html
{% extends "nasapp/base.html" %}

{% block content %}

<h1 class="display-4 text-center mt-5">Near Earth Asteroids</h1>

{% if asteroids %}
<table class="table table-lg table-bordered table-striped w-75  mx-auto mt-5">
    <thead>
        <tr class="table-info text-center">
            <th>Name</th>
            <th colspan="2">Estimated Diameter</th>
            <th class="col-md-3">Is Potentially Hazardous</th>
        </tr>
    </thead>
    <tbody>
        <tr class="table-secondary text-center">
            <td></td>
            <td><strong>Min (meters)</strong></td>
            <td><strong>Max (meters)</strong></td>
            <td></td>
        </tr>
        {% for asteroid in asteroids %}
        <tr>
            <td>{{asteroid.name}}</td>
            <td>{{asteroid.estimated_diameter.meters.estimated_diameter_min}}</td>
            <td>{{asteroid.estimated_diameter.meters.estimated_diameter_max}}</td>
            <td class="text-center">
                {% if asteroid.is_potentially_hazardous_asteroid is False %}
                    Yes
                {% else %}
                    No
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock content %}

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  <title>NASA API Demo App</title>
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand ms-2" href="{% url 'nasapp:index' %}">
        NASA API Demo
      </a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item ms-3">
          <a class="nav-link" href="{% url 'nasapp:events' %}">Event Tracker</a>
        </li>
        <li class="nav-item ms-3">
          <a class="nav-link" href="{% url 'nasapp:asteroids' %}">Near Earth Asteroids</a>
        </li>
        <li class="nav-item ms-3">
          <a class="nav-link" href="{% url 'nasapp:mars' %}">Mars Rover Photos</a>
        </li>
       
      </ul>
    </div>
  </nav>

  {%block content%}
  {%endblock content%}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
    crossorigin="anonymous"></script>

</body>

</html>

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/event.html
{% extends "nasapp/base.html" %}

{% block content %}

{% if events %}
<table class="table table-lg table-bordered table-striped w-75  mx-auto mt-5">
    <thead>
        <tr class="table-info text-center">
            <th>Title</th>
            <th>Description</th>
            <th>Source</th>
        </tr>
    </thead>
    <tbody>
        {% for event in events %}
        <tr>
            <td>{{event.title}}</td>
            <td>{{event.description}}</td>
            <td>
                {%for source in event.sources%}
                    <a href="{{event.link}}" target="_blank">{{source.url}}</a>
                {%endfor%}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <h1 class="display-3 text-center mt-5">No events found</h1>
{% endif %}

{% endblock content %}

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/events.html
{% extends "nasapp/base.html" %}

{% block content %}

<h1 class="display-4 text-center mt-5">Event Tracker</h1>

{% if all_categories %}
<table class="table table-lg table-bordered table-striped w-75  mx-auto mt-5">
    <thead>
        <tr class="table-info text-center">
            <th>Title</th>
            <th>Description</th>
            <th class="col-md-2">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for category in all_categories %}
        {% if category.title in selected_categories %}
        <tr>
            <td>{{category.title}}</td>
            <td>{{category.description}}</td>
            <td class="text-center"><a class="btn btn-primary col-md-6" href="{% url 'nasapp:event' category.id %}">View</a></td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock content %}

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/index.html
{% extends "nasapp/base.html" %}

{% block content %}

<h1 class="display-3 text-center mt-2">Astronomy Picture of the Day (APOD)</h1>

<div class="container-fluid mt-5 text-center">
    <img src="{{picture.hdurl}}" class="text-center mt-2 mx-auto" alt="{{picture.title}}" width="700" height="700" />
    <p class="h2 mt-3">{{picture.title}} ({{picture.date}})</p>
    <p class="mt-3 m-5">{{picture.explanation}}</p>
</div>

{% endblock content %}

API/ExploringSpacewithNASAapisInPython/nasapp/templates/nasapp/mars.html
{% extends "nasapp/base.html" %}

{% block content %}

<div class="container mt-5">
    <form action="" method='post' class="mx-auto">
        {% csrf_token %}
        <table class="table table-borderless mt-4">
            <tbody>
                <tr>
                    <td class="col-md-1"><label class="h5">Rover:</label></td>
                    <td class="col-md-2">
                        <select class="form-select" name="rover" aria-label="Default select example" required>
                            <option value="Spirit" {% if selected_rover == "Spirit" %}selected {% endif %}>Spirit</option>
                            <option value="Opportunity" {% if selected_rover == "Opportunity" %}selected {% endif %}>Opportunity</option>
                            <option value="Curiosity" {% if selected_rover == "Curiosity" %}selected {% endif %}>Curiosity</option>
                        </select>
                    </td>
                    <td class="col-md-1"></td>
                    <td class="col-md-1"><label class="h5">Camera:</label></td>
                    <td class="col-md-2">
                        <select class="form-select" name="camera" aria-label="Default select example"
                            required>
                            <option value="navcam" {% if selected_camera == "navcam" %}selected {% endif %}>NAVCAM</option>
                            <option value="rhaz" {% if selected_camera == "rhaz" %}selected {% endif %}>RHAZ</option>
                            <option value="fhaz" {% if selected_camera == "fhaz" %}selected {% endif %}>FHAZ</option>
                        </select>
                    </td>
                    <td>
                        <div class="form-group w-25 mx-auto">
                            <button type="submit" id="create-btn" class="form-control btn btn-primary">Fetch</button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>

{% if photos %}
<div class="w3-container mt-5">
    <div class="container-fluid">
        <div class="row">
            {% for photo in photos %}
            <div class="col-lg-3 mt-5">
                <img class="card-img-top" src="{{photo.img_src}}" width="300" height="250" class="rounded" />
                <div class="card-body">
                    <p><strong>Rover name:</strong> {{photo.rover.name}}</p>
                    <p><strong>Camera:</strong> {{photo.camera.full_name}} ({{photo.camera.name}})</p>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
    <h1 class="display-4 text-center mt-5">No photos found</h1>
{% endif %}

{% endblock content %}